# Publication tables and figures.
# All publication styling is controlled by config/figures.yml.

source(file.path(project_root(), "R", "00_utils.R"))

publication_theme <- function(base_size = 10, font_family = "sans", fig_cfg = load_figure_config()) {
  th <- fig_cfg$theme %||% list()
  margin <- unlist(th$plot_margin_pt %||% c(6, 8, 6, 8))
  ggplot2::theme_minimal(base_size = base_size, base_family = font_family) +
    ggplot2::theme(
      panel.grid.minor = ggplot2::element_blank(),
      panel.grid.major.x = ggplot2::element_blank(),
      panel.grid.major.y = ggplot2::element_line(
        linewidth = as.numeric(th$grid_line_width %||% 0.25),
        colour = th$grid_color %||% "#d9d9d9"
      ),
      axis.title = ggplot2::element_text(size = base_size),
      axis.text = ggplot2::element_text(colour = "black"),
      strip.text = ggplot2::element_text(face = "bold", hjust = 0),
      strip.background = ggplot2::element_blank(),
      legend.position = th$legend_position %||% "bottom",
      plot.margin = ggplot2::margin(margin[1], margin[2], margin[3], margin[4])
    )
}

fig_style <- function(fig_cfg = load_figure_config()) {
  list(
    font = fig_cfg$font_family %||% "sans",
    base_size = as.numeric(fig_cfg$base_size %||% 10),
    primary = fig_cfg$colors$primary %||% "#1f4e79",
    band = fig_cfg$colors$band %||% "#d9e7f3",
    zero = fig_cfg$colors$zero %||% "#6f6f6f",
    threshold = fig_cfg$colors$threshold %||% "#6f6f6f"
  )
}

save_fig1_design <- function(path) {
  # Fallback only. The publication version is generated by python/fig1_framework.py.
  stages <- data.table::data.table(
    x = c(0, 1, 2, 3),
    y = 2,
    title = c("Pre-pandemic baseline", "t0: initial shock", "t1: digital expansion", "t2: recovery"),
    detail = c(
      "Firm characteristics",
      "Sales, demand, input, cash flow",
      "First start/increase online",
      "Sales, operation, employment, input"
    )
  )
  workflow <- data.table::data.table(
    x = 0:4, y = 0,
    title = c("Strict window", "Cross-fitting", "DR signal", "Conditional curve", "Standardization")
  )
  p <- ggplot2::ggplot() +
    ggplot2::geom_segment(data = stages[-nrow(stages)],
      ggplot2::aes(x = x + 0.18, xend = x + 0.82, y = y, yend = y),
      arrow = grid::arrow(length = grid::unit(0.12, "inches"))) +
    ggplot2::geom_label(data = stages, ggplot2::aes(x = x, y = y, label = title), size = 3.2) +
    ggplot2::geom_text(data = stages, ggplot2::aes(x = x, y = y - 0.38, label = detail), size = 2.8) +
    ggplot2::geom_segment(data = workflow[-nrow(workflow)],
      ggplot2::aes(x = x + 0.18, xend = x + 0.82, y = y, yend = y),
      arrow = grid::arrow(length = grid::unit(0.10, "inches"))) +
    ggplot2::geom_label(data = workflow, ggplot2::aes(x = x, y = y, label = title), size = 3) +
    ggplot2::annotate("text", x = -0.55, y = 2, label = "Temporal design", fontface = "bold", hjust = 0) +
    ggplot2::annotate("text", x = -0.55, y = 0, label = "Estimation", fontface = "bold", hjust = 0) +
    ggplot2::coord_cartesian(xlim = c(-0.7, 4.3), ylim = c(-0.7, 2.6), clip = "off") +
    ggplot2::theme_void()
  ggplot2::ggsave(path, p, width = 10, height = 4.3, device = grDevices::cairo_pdf)
}

save_fig2_primary_curve <- function(curve, threshold, path, fig_cfg = load_figure_config()) {
  s <- fig_style(fig_cfg)
  f <- fig_cfg$fig2
  p <- ggplot2::ggplot(curve, ggplot2::aes(x = shock, y = estimate)) +
    ggplot2::geom_hline(yintercept = 0, colour = s$zero, linetype = "dashed", linewidth = as.numeric(f$zero_line_width %||% 0.38)) +
    ggplot2::geom_ribbon(
      ggplot2::aes(ymin = pointwise_lower, ymax = pointwise_upper),
      fill = s$band, alpha = as.numeric(f$band_alpha %||% 0.72), colour = NA
    ) +
    ggplot2::geom_line(colour = s$primary, linewidth = as.numeric(f$line_width %||% 0.85)) +
    ggplot2::scale_x_continuous(breaks = seq(f$x_min, f$x_max, by = f$x_break), expand = c(0, 0)) +
    ggplot2::scale_y_continuous(breaks = seq(f$y_min, f$y_max, by = f$y_break)) +
    ggplot2::coord_cartesian(xlim = c(f$x_min, f$x_max), ylim = c(f$y_min, f$y_max)) +
    ggplot2::labs(
      x = "Initial sales decline at t0 (%)",
      y = "Estimated recovery effect (percentage points)"
    ) + publication_theme(s$base_size, s$font, fig_cfg)
  if (is.finite(threshold)) {
    p <- p + ggplot2::geom_vline(
      xintercept = threshold, colour = s$threshold,
      linetype = "dashed", linewidth = as.numeric(f$threshold_line_width %||% 0.55)
    )
    if (isTRUE(f$show_threshold_point)) {
      j <- which.min(abs(curve$shock - threshold))
      p <- p + ggplot2::geom_point(
        data = curve[j], ggplot2::aes(x = shock, y = estimate),
        inherit.aes = FALSE, colour = s$primary, size = as.numeric(f$threshold_point_size %||% 1.9)
      )
    }
  }
  ggplot2::ggsave(
    path, p, width = f$width_in, height = f$height_in,
    device = grDevices::cairo_pdf
  )
}

save_fig3_severe_forest <- function(effects, path, fig_cfg = load_figure_config()) {
  s <- fig_style(fig_cfg)
  f <- fig_cfg$fig3
  d <- data.table::copy(effects)
  labels <- c(
    y_sales = "Sales recovery",
    y_continued_operation = "Business continuity",
    y_employment_retention = "Employment retention",
    y_input_recovery = "Input recovery"
  )
  d[, label := labels[outcome]]
  d[, label := factor(label, levels = rev(unname(labels)))]
  digits <- as.integer(f$label_digits %||% 1)
  fmt <- paste0("%.", digits, "f [%.", digits, "f, %.", digits, "f]")
  d[, value_label := sprintf(fmt, estimate, lower, upper)]
  p <- ggplot2::ggplot(d, ggplot2::aes(x = estimate, y = label)) +
    ggplot2::geom_vline(xintercept = 0, colour = s$zero, linetype = "dashed", linewidth = as.numeric(f$zero_line_width %||% 0.45)) +
    ggplot2::geom_errorbarh(
      ggplot2::aes(xmin = lower, xmax = upper),
      height = as.numeric(f$errorbar_height %||% 0.13), colour = s$primary, linewidth = as.numeric(f$errorbar_line_width %||% 0.65)
    ) +
    ggplot2::geom_point(colour = s$primary, size = as.numeric(f$point_size %||% 2.3)) +
    ggplot2::geom_text(
      ggplot2::aes(x = f$x_max, label = value_label),
      hjust = 1, size = as.numeric(f$label_size %||% 3.05), colour = "black"
    ) +
    ggplot2::coord_cartesian(xlim = c(f$x_min, f$x_max), clip = "off") +
    ggplot2::labs(x = "Estimated effect (percentage points)", y = NULL) +
    publication_theme(s$base_size, s$font, fig_cfg) +
    ggplot2::theme(panel.grid.major.y = ggplot2::element_blank())
  ggplot2::ggsave(
    path, p, width = f$width_in, height = f$height_in,
    device = grDevices::cairo_pdf
  )
}

save_fig4_secondary_curves <- function(curves, path, reference_shock = NULL,
                                       fig_cfg = load_figure_config()) {
  s <- fig_style(fig_cfg)
  f <- fig_cfg$fig4
  if (is.null(reference_shock)) reference_shock <- f$reference_shock %||% 50
  labels <- c(
    y_continued_operation = "a  Business continuity",
    y_employment_retention = "b  Employment retention",
    y_input_recovery = "c  Input recovery"
  )
  d <- data.table::copy(curves)
  d[, panel := factor(labels[outcome], levels = unname(labels))]
  p <- ggplot2::ggplot(d, ggplot2::aes(x = shock, y = estimate)) +
    ggplot2::geom_hline(yintercept = 0, colour = s$zero, linetype = "dashed", linewidth = as.numeric(f$zero_line_width %||% 0.34)) +
    ggplot2::geom_vline(
      xintercept = reference_shock, colour = s$threshold,
      linetype = "dashed", linewidth = as.numeric(f$reference_line_width %||% 0.45)
    ) +
    ggplot2::geom_ribbon(
      ggplot2::aes(ymin = lower, ymax = upper),
      fill = s$band, alpha = as.numeric(f$band_alpha %||% 0.72), colour = NA
    ) +
    ggplot2::geom_line(colour = s$primary, linewidth = as.numeric(f$line_width %||% 0.72)) +
    ggplot2::facet_wrap(~ panel, scales = "fixed", nrow = 1) +
    ggplot2::scale_x_continuous(breaks = seq(f$x_min, f$x_max, by = f$x_break), expand = c(0, 0)) +
    ggplot2::coord_cartesian(xlim = c(f$x_min, f$x_max), ylim = c(f$y_min, f$y_max)) +
    ggplot2::labs(
      x = "Initial sales decline at t0 (%)",
      y = "Estimated effect (percentage points)"
    ) + publication_theme(s$base_size - 1, s$font, fig_cfg) +
    ggplot2::theme(strip.text = ggplot2::element_text(face = "bold", hjust = 0))
  ggplot2::ggsave(
    path, p, width = f$width_in, height = f$height_in,
    device = grDevices::cairo_pdf
  )
}

severe_outcome_table <- function(fits, cfg) {
  data.table::rbindlist(lapply(names(fits), function(outcome) {
    z <- weighted_dr_effect(fits[[outcome]]$data, quote(severe_shock == 1L))
    scale <- if (outcome == "y_sales") 1 else 100
    ci <- ci_from_estimate(z$estimate, z$se, cfg$inference$pointwise_level)
    data.table::data.table(
      outcome = outcome, estimate = scale * z$estimate, se = scale * z$se,
      lower = scale * ci[1], upper = scale * ci[2], n = z$n
    )
  }))
}

sample_panel_b <- function(windows, balance) {
  # Unadjusted treatment/control summaries shown beside post-adjustment SMDs.
  d <- windows
  get_smd <- function(pattern) {
    z <- balance[grepl(pattern, covariate, fixed = TRUE)]
    if (!nrow(z)) return(NA_real_)
    z$abs_after[which.max(z$abs_after)]
  }
  pct <- function(v, arm) 100 * weighted_mean(as.numeric(v[d$treatment == arm]), d$analysis_weight[d$treatment == arm])
  mean_arm <- function(v, arm) weighted_mean(as.numeric(v[d$treatment == arm]), d$analysis_weight[d$treatment == arm])

  input_decline <- as.integer(d$t0_input_state == 3)
  cash_decline <- as.integer(d$t0_cash_flow_state == 3)
  data.table::data.table(
    variable = c(
      "Number of firms", "Baseline employment, mean", "Firm age, years",
      "Pre-pandemic website, %", "First-wave sales decline, %",
      "First-wave input supply decline, %", "First-wave cash-flow decline, %"
    ),
    treated = c(
      sum(d$treatment == 1L),
      mean_arm(d$baseline_employment, 1), mean_arm(d$firm_age, 1), pct(d$website, 1),
      mean_arm(d$shock_sales_decline, 1), pct(input_decline, 1), pct(cash_decline, 1)
    ),
    control = c(
      sum(d$treatment == 0L),
      mean_arm(d$baseline_employment, 0), mean_arm(d$firm_age, 0), pct(d$website, 0),
      mean_arm(d$shock_sales_decline, 0), pct(input_decline, 0), pct(cash_decline, 0)
    ),
    post_adjustment_smd = c(
      NA_real_, get_smd("baseline_employment"), get_smd("firm_age"), get_smd("website"),
      get_smd("shock_sales_decline"), get_smd("t0_input_state"), get_smd("t0_cash_flow_state")
    )
  )
}
